### ISSUE TITLE
Integration with existing projects

### ISSUE THREAD

**Issue by Vaberer** [JiriTrecak/Laurine#1]
Hello,

Your library seems to be very handy and I really consider it to use it in my projects. What I would appreciate is to somehow help me to substitute all my current ```NSLocalizedString()``` in my code into your approach. Because manually changing all my strings is pretty big task and it would definitely be able to do it just with one command/script.

Thanks.

Best,
Patrik

**Comment by JiriTrecak** [comment]
Hey Patric,

It is definitely something I would like to do in the future - I understand that some project are just massive and if there is a way how to automate it, that would make a lot of people happy. 

I am putting it to queue for version 0.3, after ObjC support is out, it is definitely task worth doing but would require some changes to the main generator, or maybe I would create it as standalone tool - so it will need more time, but it is definitely coming!

Thanks for your feedback!
Jiri

**Comment by JiriTrecak** [comment]
I've put this tool into solid roadmap - it is coming in version 0.4, after plural and gender support is out. Thank you!
