### ISSUE TITLE
Special characteres issue

### ISSUE THREAD

**Issue by ed-mejia** [JiriTrecak/Laurine#14]
Hi,

In my localization file I have an string like this:
```
reset-pass-label = "Enter your email address below and we'll \r\n send you a new password";
```

I used ***\r\n*** because I need to break the line at that point, the problem is that the generated Swift file looks like this:

```
/// Base translation: Enter your email address below and we'll 
 send you a new password
    public static var ResetPassLabel : String = "reset-pass-label".localized
```
Somehow the break line is being applied to the source code as well, as a result the file does not compile.

**Comment by JiriTrecak** [comment]
Hey,

It has been fixed already, but the change apparently did not make it to master. I merged everything so the branches are in sync - just download new version of the generator and it should work - I tested with your string and had no problem.

JT

**Comment by ed-mejia** [comment]
Great! thanks now it's working perfect :tada:
