### ISSUE TITLE
error: unknown attribute 'exported'

### ISSUE THREAD

**Issue by Ewg777** [JiriTrecak/Laurine#22]
Version 7.3 beta (7D129n)
```sh
/usr/local/bin/LaurineGenerator.swift:47:2: error: unknown attribute 'exported'
@exported import Darwin
```

```sh
~: brew install jiritrecak/laurine/laurine
Warning: jiritrecak/laurine/laurine-0.2.0 already installed
```

**Comment by wess** [comment]
:+1:

**Comment by JiriTrecak** [comment]
Hello guys!

Sorry it took me so long - I've been unavailable for few weeks, but I am back in business!

I have Laurine modified for version 7.3 already, but I am still making some changes and adding more features, so it might take little more time - but by the time 7.3 is released - possibly sooner, it will be ready to comply once again.

For now, thanks for trying it and I will let you know here once this is done.

Sincerely
JT

**Comment by amelnychuck** [comment]
Any update on the availability date of the fix, or maybe a chance of making a fix branch for this issue in the meantime?

**Comment by JiriTrecak** [comment]
Hello guys, I just pushed the fix and first batch of updates that I am doing, could you try? :)) Should work for both 7.2 and 7.3.

Thanks!

**Comment by Ewg777** [comment]
@JiriTrecak Awesome! Thanks!
