### ISSUE TITLE
SwiftLint Violations

### ISSUE THREAD

**Issue by Dschee** [JiriTrecak/Laurine#23]
I just started using Laurine in a project that also uses SwiftLint to ensure code conventions. It appears that Laurines produced code does not comply to some conventions, for example I get this:

`warning: Colon Violation: Colons should be next to the identifier when specifying a type. (colon)`

Could we make the generated code comply to the Swift conventions expressed by https://github.com/realm/SwiftLint?

**Comment by JiriTrecak** [comment]
Hello!

Sorry it took me so long - I've been unavailable for few weeks, but I am back in business!

The next version of Laurine is surely coming soon and I am definitely making sure it complies under linted project, even with strict settings.

For now, thanks for trying it and I will let you know here once this is done.

Sincerely
JT

**Comment by Dschee** [comment]
Still nothing happened here, right? At least I'm still seeing all the warnings ... do you plan updating anytime soon?
