### ISSUE TITLE
Xcode 7.3 support

### ISSUE THREAD

**Issue by pixeldock** [JiriTrecak/Laurine#31]
First of all: Thanks for developing and sharing Laurine, I really like it a lot!

Unfortunately with the recent release of Xcode 7.3 `Laurine Generator` produces the following error and warnings:

![bildschirmfoto 2016-03-24 um 10 48 02](https://cloud.githubusercontent.com/assets/540645/14013656/ed79fb52-f1ad-11e5-9086-19b6ea223d92.png)

**Comment by JiriTrecak** [comment]
Hello!

Thanks for using it :) I updated Brew few minutes ago, so when you do brew / update latest version (if you have it installed locally), then you will have the latest version with all the fixes. (v0.2.2)

If you have downloaded Laurine directly, please download LaurineGenerator.swift directly from master and replace your current version with it (works in 7.3). I will go through example project now if everything works there.

**Comment by JiriTrecak** [comment]
So I just tested and it works okay, I also just removed the warnings so it does not show anything in the project. Hope it will work flawlessly for you now!

Sincerely,

Jiri T

**Comment by pixeldock** [comment]
Thanks for the quick reply! 

I just added the latest version of LaurineGenerator and now I get the following errors (in Xcode 7.3):

![bildschirmfoto 2016-03-24 um 11 18 42](https://cloud.githubusercontent.com/assets/540645/14014424/a4fc0410-f1b2-11e5-9573-d9a68517ba35.png)

![bildschirmfoto 2016-03-24 um 11 19 04](https://cloud.githubusercontent.com/assets/540645/14014434/b36fbd84-f1b2-11e5-88f9-d0cce44184b3.png)

**Comment by JiriTrecak** [comment]
Yes, this happens when you connect Laurine to project (that the LaurineGenerator.swift can be found in your project tree). You have to run it either through command line, OR through build script. XCode does not allow top-level expressions when compiling your project, which is exactly what you are encountering.

**Comment by pixeldock** [comment]
It works, no warnings. Thanks a lot!

**Comment by JiriTrecak** [comment]
No problem, glad to help.

Have a nice day!

JT
