### ISSUE TITLE
Deprecated homebrew dependencies

### ISSUE THREAD

**Issue by esetnik** [JiriTrecak/Laurine#37]
```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/jiritrecak/homebrew-laurine/laurine.rb:4:in `<class:Laurine>'
Please report this to the jiritrecak/laurine tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/jiritrecak/homebrew-laurine/laurine.rb:4:in `<class:Laurine>'
Please report this to the jiritrecak/laurine tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/jiritrecak/homebrew-laurine/laurine.rb:4:in `<class:Laurine>'
Please report this to the jiritrecak/laurine tap!
```

**Comment by rlester** [comment]
Now its an error: 

`Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/jiritrecak/homebrew-laurine/laurine.rb:4:in `<class:Laurine>'
Please report this to the jiritrecak/laurine tap!
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:86:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:94:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/sha1.rb:3:in `sha1'
/usr/local/Homebrew/Library/Taps/jiritrecak/homebrew-laurine/laurine.rb:4:in `<class:Laurine>'
/usr/local/Homebrew/Library/Taps/jiritrecak/homebrew-laurine/laurine.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:200:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:240:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:271:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:254:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1357:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1355:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1355:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:37:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'`

**Comment by jormungand** [comment]
quick local fix:

```bash
$ vi /usr/local/Homebrew/Library/Taps/jiritrecak/homebrew-laurine/laurine.rb
```

```diff
diff --git a/laurine.rb b/laurine.rb
index 8a507a0..4c1e06e 100644
--- a/laurine.rb
+++ b/laurine.rb
@@ -1,7 +1,7 @@
 class Laurine < Formula
   homepage "https://github.com/JiriTrecak/Laurine/"
   url "https://github.com/JiriTrecak/Laurine/archive/0.2.2.tar.gz"
-  sha1 "1a80770ee4a52ca830b97e934aa6a06aa6cf435b"
+  sha256 "909a5a495fb21fa7e20b823b6415f4b33b609dba341ea603d68dffe331f92946"
   version "0.2.2"
 
   def install
```

**Comment by JiriTrecak** [comment]
Merged the fix, thank you all for your work <3
