### ISSUE TITLE
Swift 3 Support?

### ISSUE THREAD

**Issue by ed-mejia** [JiriTrecak/Laurine#38]
Any plans to update the project to swift 3?

If you need a hand just create a branch and I could help.

**Comment by JiriTrecak** [comment]
Would definitely be appreciated! I have it on my list, but I know that there are people that already use it. I will branch it. There shouldn't be any changes to exported class / structure, I assume, the only real issue is the code of the export script.

Thank you, 
Jiri

**Comment by JiriTrecak** [comment]
I've created a new branch for this task:
https://github.com/JiriTrecak/Laurine/tree/swift-3

**Comment by ed-mejia** [comment]
Cool! 👍

**Comment by ed-mejia** [comment]
Hi @JiriTrecak 

I submitted a pull request that updates the generator for the new Swift 3 syntax and changes, I did not migrate the Example project though.

The example project contains another library of yours (**Warp**) that needs to be migrated first, I personally think that this example is too elaborated for the purpose of this library but anyway if you migrate that library I could give a hand to migrate the example as well.

In the meantime this PR https://github.com/JiriTrecak/Laurine/pull/39 will work to give support to the Generator.

**Comment by nikitabelosludtcev** [comment]
Can I continue to use Swift 2.2 to generate localizations files? I need to publish my project to the Appstore, but I can't do it without localizations(

**Comment by JiriTrecak** [comment]
@nikitabelosludtcev  Hey, you should absolutely be able to do it - I will be changing master to 3.0 version over the coming weekend, however, I will keep legacy 2.2 version on the new branch until support is dropped. 

In the new XCode, 2.3 is supported and 3.0 is supported, but if you need to finish it on 2.2, I advise you to download XCode 7.3.1 and have it installed on your machine as well https://developer.apple.com/download/more/ - therefore avoiding the need to convert it or anything.

**Comment by nikitabelosludtcev** [comment]
Please... make Xcode 8 support, we really need it. 
https://github.com/qmchenry/Laurine/commit/fd8116a2f254bd0ff050c80dfecce85ab9cffd80 this commit works buggy.

**Comment by JiriTrecak** [comment]
Working on it :)

**Comment by pgorzelany** [comment]
Any news about this?

**Comment by JiriTrecak** [comment]
I expect to have it within few hours, I am current working on my startup that we hope will change the mobile programming as we know it, so it is quite time-consuming. But this is now the top priority for everyone, so expect it today.

If you are interested - http://supernova.studio/coming-soon/ :) Sorry for delays guys!

**Comment by JiriTrecak** [comment]
Just quick update, working through conversion, missing few last things and then some heavy testing, if everything works, then we are golden :)

**Comment by bhallamohit** [comment]
hi @JiriTrecak 

Can you please commit these changes, ASAP.

**Comment by JiriTrecak** [comment]
@bhallamohit they are already there:
https://github.com/JiriTrecak/Laurine/tree/master-3
I am still working on resolving some issues that are due to changes that needed to be made, but most of the stuff already works.

**Comment by JiriTrecak** [comment]
The version for 3.0 is here - tested and fully working.
https://github.com/JiriTrecak/Laurine/tree/master-3

I will be moving it to master and create 2.2 branch this afternoon, after which everything should be solved and working for both versions.

Have a good one everyone!

**Comment by bhallamohit** [comment]
thnx jiri,

for showing concern.

Thanks,



​--

Mohit Bhalla |Jr. Associate - IT
mohit.bhalla@daffodilsw.com <sachin.mehndiratta@daffodilsw.com>
15th Floor, Block A3,

DLF Ltd SEZ, Silokhera,

Sec-30, Gurgaon, Haryana (India)

Mobile: +91-9999723485
Phone : +91-0124-4742150
Web :   www.daffodilsw.com

**Comment by JiriTrecak** [comment]
Laurine now supports 2.2 / 3.0 properly:

Swift 3.0
https://github.com/JiriTrecak/Laurine

Swift 2.2
https://github.com/JiriTrecak/Laurine/tree/Swift-2.2

If you find any issues with it, please open the new ticket. Have a great one!

**Comment by jamesbebbington** [comment]
Hey @JiriTrecak could you tag a new release with Swift 3.0 support please. I'm seeing `0.2.2` back from March 24th as the latest on GitHub and Homebrew. Thanks.

**Comment by seyhunak** [comment]
@JiriTrecak Still no Swift 3 support? Version 0.2.2 in Homebrew. Any updates for Swift 3? Thanks.
