### ISSUE TITLE
Allow to be used within frameworks

### ISSUE THREAD

**Issue by ed-mejia** [JiriTrecak/Laurine#4]
Hi, First of all I must to say this Lib is Just AWESOME!..

One thing is that in my project I'm using a framework to share functionality between extensions and the App, said that I want to keep every single localization string within the framework so it can be used by all the extensions and the App itself.

But at the moment it's not working because the generated code are not public.

**Comment by JiriTrecak** [comment]
Hey! Thank you for the kind words.

You are right - this is something that should be done. I made it public to the master ; it is needed change - you can download the new version and it should work :)

Have a nice day and let me know if it is okay so I can close it!
Jiri

**Comment by ed-mejia** [comment]
@JiriTrecak  works like a charm!!!, thanks! :+1:

**Comment by JiriTrecak** [comment]
Glad to hear :)
