### ISSUE TITLE
Can't build Laurine with Swift 2.2 on Mac Sierra

### ISSUE THREAD

**Issue by nikitabelosludtcev** [JiriTrecak/Laurine#40]
I trying to build it from Terminal but receive the error.
Do you know what's the problem?
![unspecified](https://cloud.githubusercontent.com/assets/1511214/18750571/bcb9b6d2-80ec-11e6-85de-ae938e56d6dd.png)

**Comment by JiriTrecak** [comment]
Once I am done with the changes for 3.0, I will look into it., not sure. But This seems that it is not connected to Laurine itself.. Maybe look at something like this:
http://stackoverflow.com/questions/34180163/xcode-7-2-could-not-build-objective-c-module

Seems similar to your issue. Please let me know if you solved it, as I will want to support 2.2 version as well and this issue might affect more people.

**Comment by JiriTrecak** [comment]
@nikitabelosludtcev any luck solving your problem? I tested thoroughly a did not encounter this issue, maybe something about configuration?
