### ISSUE TITLE
How to use this with many languages?

### ISSUE THREAD

**Issue by adamszeremeta** [JiriTrecak/Laurine#42]
Hello,
currently I have one language supported in app but soon I have to add another. How this script should be configured to support both languages without changes in code?

**Comment by JiriTrecak** [comment]
Hey, I assume you already figured out? :) You only provide one (english) file to Laurine, all translations are taken through keys as you would normally. Internally, Laurine uses the same localization system present natively in iOS, no exceptions.

Have a great day,

Jiri
