### ISSUE TITLE
Laurine's younger Sister - Image Generator [name pending]

### ISSUE THREAD

**Issue by JiriTrecak** [JiriTrecak/Laurine#43]
Hello everyone,

I was thinking about making the same generator as Laurine for the image assets as well since the base is solid and resource generators that are available do not seem to do the job properly. It would work the same way, with similar options, through command-line or as build script - with a primary goal to generate nested result that you would use similarly as Laurine:

`Localizations.Profile.Header` vs `Images.Profile.HeaderBar`

There would also be a convenience to directly instantiate images (`.image`) or something similar, to get rid of `UIImage(named: Images.Name)` altogether.

What are your thoughts about that? Would you like something like this?

Have a great day,

Jiri

**Comment by robtimp** [comment]
@JiriTrecak I think this could be very useful.

**Comment by ed-mejia** [comment]
Not sure how useful could be, now that we have image [literals](https://developer.apple.com/swift/blog/?id=33)
