### ISSUE TITLE
Swift 4 migration

### ISSUE THREAD

**Issue by pgorzelany** [JiriTrecak/Laurine#51]
Just tried to migrate a project to Swift 4 and it gives me an error on the Laurine build phase. Should probably be updated for Swift 4.

**Comment by JiriTrecak** [comment]
Hey Piotr,

I will be working on Swift 4 sometime over next few weeks as it is still being finalized. If you need it till then, I suggest forking it and (if you wish) even providing pull request, I can create S4 branch for it sooner.

As a workaround, it should be possible to force the compiler to compile Laurine in Swift 3 (-swift-version 3 compiler option for the dependency), though I haven't tested it myself yet.

Sincerely,
Jiri

**Comment by JiriTrecak** [comment]
Please do refer to #52 for any further comments.
