### ISSUE TITLE
Objc localization - String with format specifiers

### ISSUE THREAD

**Issue by IordacheClaudiu** [JiriTrecak/Laurine#55]
Hi,
When I try to create the localization for Obj-C the script generates the following method:
```
/// Base translation: GO TO %@
- (NSString *(^)(NSString *))BenefitsGoToButtonTitle;
```
Is this the desired behaviour?
Best regards.

**Comment by JiriTrecak** [comment]
This is correct because this is the only way how I can preserve the dot behavior in Obj-C (say people.header.title(x)). It is also a very performant solution - be it that the definition is little wild. Hope it helps :)

Cheers, Jiri
