### ISSUE TITLE
Support multi-line strings

### ISSUE THREAD

**Issue by Ewg777** [JiriTrecak/Laurine#6]
My Localizable.strings contains
```swift
"Message" = "WTF\r\nWTF";
```
Laurine generates 
```swift
    /// Base translation: WTF
WTF
    static var Message: String = "Message".localized
```
Swift Compiler Error Localizations.swift:64:1: Expected declaration

**Comment by JiriTrecak** [comment]
Hello and welcome,

Yes, this is correct. What it actually generates is "$KEY".localized, not "$VALUE".localized ; .localized is extension to String type, that takes that key and converts it to value using NSLocalizedString:

NSLocalizedString("Message", comment: nil) –> which when used in your code will produce "WTF\r.."

Hope it helps!

**Comment by JiriTrecak** [comment]
Hey Ewg,

Thank you for your feedback - I will look into it as soon as possible, as this really breaks a lot of functionality. Will let you know when it is ready.

Sincerely,
Jiri

**Comment by JiriTrecak** [comment]
It is fixed - generator accounted for \n, but not for \r and the comment showed up on the next line. I will make more clever solution in the future so it renders whole string to multiline comment, but for now I am just replacing it with empties.

Change is in master and working.

Enjoy!
