### ISSUE TITLE
Keys as language keywords

### ISSUE THREAD

**Issue by Vaberer** [JiriTrecak/Laurine#8]
Hello Jiri,

I coincidentally bumped into a problem where I used a key ```YES``` and apparently yes is also a keyword in Objective-C so a generated code could not compile. I suggest to use a key but with a prefix. Do you have any other/better solution?

Best,

Patrik

**Comment by JiriTrecak** [comment]
Hey Vaberer,

Thanks for noticing - This will require some deeper research as I would have to go through all, but should really be done. Currently, I am prefixing keys with _ where it is needed - for example, if your key starts with number (as, for example, "10thClass" is not valid name of property and will fail in both objc & swift).

If you would like to help with that and possibly make pull request, this is the part that you are interested in:

    private func variableName(string : String) -> String {
        
        if self.autocapitalize {
            return (string.isFirstLetterDigit() ? "_" + string.camelCasedString : string.camelCasedString)
        } else {
            return (string.isFirstLetterDigit() ? "_" + string : string)
        }
    }

This should have added one more check for if it contains keywords:

    return (string.isFirstLetterDigit() || string.isKeyword() ?....

Now the only thing that needs to be done is to list those keywords and think through if it is needed to have them all (there will be differences in languages). I will look into it once I am finished with features of 0.3, if you have something before that, it would be great (plus you would get into "hall of fame"). 

Thank you!
